
%dw 2.0
output application/java 
---
[{
    customerId : "3366745010234373b59",
    customerName : "qui",
    customerIdProof : "cupidatat",
    Gender : "female",
    PhoneNumber : 77,
    CustomerCity : "nostrud",
    HotelId : 27,
    NameOfHotels : "sed",
    Numberofrooms : 72,
    NumberOfPeople : 48,
    roomType : "voluptas",
    bedsize : "ipsam",
    AirConditioner : "est,",
    emptyrooms : 60,
    availability : 79,
    address : "Castro St 89",
    city : 86,
    priceperday : 28,
    startDate : 19,
    endDate : 80,
  },
{
    customerId : "a95dcef58fca4e87ac1",
    customerName : "quis",
    customerIdProof : "et",
    Gender : "female",
    PhoneNumber : 98,
    CustomerCity : "aliquam",
    HotelId : 7,
    NameOfHotels : "voluptatem.",
    Numberofrooms : 81,
    NumberOfPeople : 23,
    roomType : "veniam,",
    bedsize : "tempor",
    AirConditioner : "explicabo.",
    emptyrooms : 76,
    availability : 72,
    address : "Second Ave 21",
    city : 3,
    priceperday : 72,
    startDate : 72,
    endDate : 7,
  }]
