#%RAML 1.0 NamedExample
value:
  -
    id:  18955A0334
    name: Ram
    idProof:  pan card
    gender:  female
    phoneNumber:   +91-8976598848
    city:  Bangalore
    

  -
    id:  20955A0453
    name: Kumar
    idProof:  aadhaar card
    gender:  male
    phoneNumber:  +91-9848671256
    city:  Hyderabad
    
   

  -
    id:  20955A0239
    name: Jyothi
    idProof:  voter Id
    gender:  female
    phoneNumber:  +91-7876289971
    city:  Mumbai
   