#%RAML 1.0 NamedExample
value:
    id: 18955A0334
    hotelId: 102272
    nameOfHotel: OYO
    numberOfRooms:  1
    numberOfPeople:  3
    roomType:  standard
    bedSize:  king
    airConditioner:  true
    availability:  12
    address:  Near St.Philomena's Hospital, Xavier LayOut, Bangalore
    city:  Bangalore
    pricePerDay:  2000
    startDate:  10-Apr-2000
    endDate:  15-May-2045

    